services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socket-box.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.socket-box.entrypoints=https"
      - "traefik.http.routers.socket-box.tls=true"
      - "traefik.http.routers.socket-box.tls.certresolver=letsencrypt"
      - "traefik.http.services.socket-box.loadbalancer.server.port=5000"
      - "traefik.http.services.socket-box.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.socket-box.loadbalancer.sticky.cookie.name=io"

networks:
  coolify:
    external: true